name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - run: npm ci
      - run: npm test
